steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/tougou-db-f9f9e/cloud-run-source-deploy/legend-chat-api:latest', '.']
images:
  - 'asia-northeast1-docker.pkg.dev/tougou-db-f9f9e/cloud-run-source-deploy/legend-chat-api:latest'
